### PR TITLE
Renamed escher->escher_server to fix #53.

### LINKED ISSUE #53: Freezing on include(Pkg.dir("Escher", "src", "cli", "serve.jl")) and escher --serve to API macro's use of `=>` is broken on Julia v0.4
I've been following the installation / usage instructions for Escher here: https://shashi.github.io/Escher.jl/ and am running into a problem on `Version 0.4.0-dev+6112 (2015-07-20 17:52 UTC) Commit 189a043 (3 days old master)`:

```
julia> using Escher

julia> include(Pkg.dir("Escher", "src", "cli", "serve.jl"))

WARNING: deprecated syntax "tags (" at /Users/seth/.julia/v0.4/Hiccup/src/Hiccup.jl:87.
Use "tags(" instead.

WARNING: deprecated syntax "exporttags (" at /Users/seth/.julia/v0.4/Hiccup/src/Hiccup.jl:95.
Use "exporttags(" instead.

WARNING: deprecated syntax "expand (" at /Users/seth/.julia/v0.4/Lazy/src/macros.jl:30.
Use "expand(" instead.

WARNING: deprecated syntax "switch (" at /Users/seth/.julia/v0.4/Lazy/src/macros.jl:62.
Use "switch(" instead.

WARNING: deprecated syntax "> (" at /Users/seth/.julia/v0.4/Lazy/src/macros.jl:111.
Use ">(" instead.

WARNING: deprecated syntax ">> (" at /Users/seth/.julia/v0.4/Lazy/src/macros.jl:132.
Use ">>(" instead.

WARNING: deprecated syntax "as (" at /Users/seth/.julia/v0.4/Lazy/src/macros.jl:159.
Use "as(" instead.

WARNING: deprecated syntax "_ (" at /Users/seth/.julia/v0.4/Lazy/src/macros.jl:177.
Use "_(" instead.

WARNING: deprecated syntax "or (" at /Users/seth/.julia/v0.4/Lazy/src/macros.jl:181.
Use "or(" instead.

WARNING: deprecated syntax "dotimes (" at /Users/seth/.julia/v0.4/Lazy/src/macros.jl:193.
Use "dotimes(" instead.

WARNING: deprecated syntax "oncethen (" at /Users/seth/.julia/v0.4/Lazy/src/macros.jl:205.
Use "oncethen(" instead.

WARNING: deprecated syntax "defonce (" at /Users/seth/.julia/v0.4/Lazy/src/macros.jl:222.
Use "defonce(" instead.

WARNING: deprecated syntax "with (" at /Users/seth/.julia/v0.4/Lazy/src/macros.jl:236.
Use "with(" instead.

WARNING: deprecated syntax "cond (" at /Users/seth/.julia/v0.4/Lazy/src/macros.jl:252.
Use "cond(" instead.

WARNING: deprecated syntax "errs (" at /Users/seth/.julia/v0.4/Lazy/src/macros.jl:275.
Use "errs(" instead.

WARNING: deprecated syntax "dynamic (" at /Users/seth/.julia/v0.4/Lazy/src/dynamic.jl:73.
Use "dynamic(" instead.

WARNING: deprecated syntax "rec (" at /Users/seth/.julia/v0.4/Lazy/src/tail.jl:53.
Use "rec(" instead.

WARNING: deprecated syntax "bounce (" at /Users/seth/.julia/v0.4/Lazy/src/tail.jl:89.
Use "bounce(" instead.

WARNING: deprecated syntax "bounce (" at /Users/seth/.julia/v0.4/Lazy/src/tail.jl:102.
Use "bounce(" instead.

WARNING: deprecated syntax "app (" at /Users/seth/.julia/v0.4/Mux/src/server.jl:14.
Use "app(" instead.
```
... and here it appears to hang. No other output, no listening port, no return to REPL until I hit ^C.

### PR DESCRIPTION
**Pull request by rohitvarkey**

### CODE REVIEW

**Comment by aviks** [comment]
`escherd` ?

**Comment by shashi** [comment]
It's not only a server, you can also compile to html with it...

Also, I believe if this file is getting loaded when `using Escher` is run, shouldn't this be a Julia bug?

**Comment by rohitvarkey** [comment]
@shashi I just wanted to prod you to rename it to whatever you wanted to rename it to. :stuck_out_tongue: 

And I'm not sure if it is a Julia bug. Is there a specification that only files with `.jl` extensions will be loaded? Incidentally, the `0.3.10` version also exhibits the same behavior as in loading in the `bin/escher` file when `using Escher`  is run from a REPL launched from `bin/escher` directory.

**Comment by shashi** [comment]
Opened https://github.com/JuliaLang/julia/issues/12340 let's see if this is a bug or a feature.

**Comment by shashi** [comment]
This is resolved on Julia master. https://github.com/JuliaLang/julia/pull/12356 does this problem arise on 0.3 as well?

**Comment by aviks** [comment]
> does this problem arise on 0.3 as well

While the particular issue about loading files without a `.jl` suffix exists in 0.3, due to the different search behaviour, it wouldn't be a problem, I think.

**Comment by rohitvarkey** [comment]
@aviks Yes. Unless you do `./escher` when your `pwd` is `~/.julia/v0.3/Escher/bin`. 

But I don't think a rename is necessary anymore. Just a warning in the docs would suffice?

**Comment by shashi** [comment]
Ok, closing this.

**Pull request closed without merging**
