### PR TITLE
Layout user guide.

### PR DESCRIPTION
**Pull request by rohitvarkey**
I've created a layout user guide using tiles of colors laid out in different fashions. I wasn't sure what `packlines` does, so just copy pasted the description from the api docs. I think I've covered everything listed in the index file under layout, except for *Absolute Positioning*. Borders and colors have been explained in theme.jl (which we should link to from the index page in some form).

I also moved all the user guide files to a `user-guide` directory to differentiate them from the normal examples and added links to the content and layout.

Do go through and let me know what you think!

cc: @shashi, @NOTtheMessiah, @alinchis

### CODE REVIEW

**Comment by alinchis** [comment]
The guide looks great.
I have a question:
should each example contain all necessary code, or it can rely on previous examples? I have the same dilemma regarding the Escher Guide, in particular the `sierpinski` function. If someone who is relatively familiar with Julia tries to run an example without reading the previous ones, it won't work.

**Comment by alinchis** [comment]
the example code seems to be editable, is it intended like this?

**Comment by rohitvarkey** [comment]
I was trying to build up on the `colortile` function and try and explain things like that. But I did try and include most of the code required to just reproduce by copy pasting unless the code became too big and unwieldy. I think it's okay to expect users to understand and copy paste old examples also if errors are thrown, like for the `sierpinski` definition. But yeah, comments would clear any possible the confusion too.

> the example code seems to be editable, is it intended like this?

I'd prefer it to be not editable too. I was just using the `listing` function used to create the other guides. Will look into making it not editable.

**Comment by shashi** [comment]
@rohitvarkey looking good! have you seen http://escher-jl.org/layout-guide.html ? Could pull in some stuff from it in the future..
@alinchis I think they need not be always fully self-contained. Stuff like `sierpinski` is very much fine to not repeat. Yes the cells are editable, you can hit ctrl+enter to run the code.

**Comment by rohitvarkey** [comment]
@shashi Totally forgot about that page. Will try and incorporate stuff from there, but I think I'll move onto widgets now and come back to layouts later. Can you add a section on absolute positioning and also explain `packlines` correctly?

I missed out on `hskip` and `vskip` too!

**Comment by shashi** [comment]
@rohitvarkey I'll do it soon. Thanks! it looks like the code is not showing up on the layout-guide page.

**Pull request merged**
