### PR TITLE
Modernize Travis configuration

### PR DESCRIPTION
**Pull request by tkelman**

### CODE REVIEW

**Comment by randyzwitch** [comment]
LGTM. The failure here is with Escher and ComposeDiff, not changing the Travis file itself.

**Comment by shashi** [comment]
Okay, now it segfaults on the release build. Oddly enough it's all good on nightly...

**Comment by shashi** [comment]
For me locally on 0.5-rc3, it segfaulted only on the first run of tests, works fine when run again.

**Comment by tkelman** [comment]
https://github.com/shashi/Escher.jl/issues/176 ?

**Comment by shashi** [comment]
@TotalVerb mentioned that it was failing on nightly, this is the release build

**Pull request merged**
